server:
  port: 8080 # Port address for localhost. Ex: http://localhost:8080/api/v1/customers/2
  error:
    include-message: always # Display error message when an exception occurs in an API call.

spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/customers
    username: postgres
    password: 34221719
    driver-class-name: org.postgresql.Driver

  flyway:
    baseline-on-migrate: true
    baseline-version: 1
    enabled: true

  jpa:
    hibernate:
      ddl-auto: none # validte that flyway created scheamas are correct. If not error get.
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    open-in-view: false # used to avoid warning This is a general warning. If you are not performing database queries in the view layer, you can safely ignore it.
  main:
    web-application-type: servlet
